---
title: "NC Discharge Analysis (New River)"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# getting directory
getwd()

# loading packages
library(ggplot2)
library(tidyverse)
library(lubridate)
library(dplyr)

# loading in data
NewRiver.Discharge.RAW <- read.csv("../Data/Raw/NC_Discharge_NewRiver_RAW.csv")

# setting date column as date
NewRiver.Discharge.RAW$Date <- as.Date(NewRiver.Discharge.RAW$datetime, format = '%m/%d/%y')

# initial tidying of dataset
NewRiver.Discharge.RAW <- NewRiver.Discharge.RAW[-c(1), ] # removing non-data row

NewRiver.Discharge.PROC <- NewRiver.Discharge.RAW %>% 
                        select(agency_cd, site_no, 
                               X89345_00060, X89346_00065, Date) #selecting necessary columns

colnames(NewRiver.Discharge.PROC) <- c("Agency", "Site_No",
                                       "Discharge_cfs", "GageHeight_ft", "Date") # changing column names
  
# setting discharge and gage height columns as numeric
NewRiver.Discharge.PROC$Discharge_cfs <- as.numeric(NewRiver.Discharge.PROC$Discharge_cfs)
NewRiver.Discharge.PROC$GageHeight_ft <- as.numeric(NewRiver.Discharge.PROC$GageHeight_ft)

NewRiver.Discharge.PROC <- NewRiver.Discharge.PROC %>% 
                        group_by(Date) %>%  # grouping by date
                        mutate(Year = year(Date), # creating year column
                               Month = month(Date), # creating month column
                               Day = day(Date)) %>% # creating day column
                        filter(Year >= 1990) # filtering for data 1990 or later
                        
# creating daily discharge dataset
NewRiver.Daily.DischargeGage <- NewRiver.Discharge.PROC %>%  
                        summarise(MeanDailyDischarge_cfs = mean(Discharge_cfs), # daily mean discharge
                                  MeanDailyGageHeight_ft = mean(GageHeight_ft)) # daily mean gage height

```

